workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_TAG
      when: never
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_COMMIT_BRANCH == 'cicd'

stages:
  - build_and_test
  - version
  - release

variables:
  OMPI_ALLOW_RUN_AS_ROOT: 1
  OMPI_ALLOW_RUN_AS_ROOT_CONFIRM: 1

compile-and-test-2D:
  image: "ubuntu:latest"
  stage: build_and_test
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
  before_script:
    - echo 'debconf debconf/frontend select Noninteractive' | debconf-set-selections
    - DEBIAN_FRONTEND=noninteractive apt-get -qq update && apt-get -qq -y --no-install-recommends install tzdata
    - cp /usr/share/zoneinfo/Europe/Madrid /etc/localtime
    - apt-get -qq install -y build-essential git cmake xxd
    - apt-get -qq install -y python3-numpy python3-dev python-is-python3
    - apt-get -qq install -y libxerces-c-dev libmuparser-dev
    - apt-get -qq install -y llvm-dev clang libclang-dev
    - apt-get -qq install -y ocl-icd-opencl-dev pocl-opencl-icd
    - apt-get -qq install -y libopenmpi-dev libvtk9-dev
    - mkdir -p build2D
    - mkdir -p install2D
  script:
    - cmake -B build2D/ -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=install2D -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON -DAQUAGPUSPH_3D:BOOL=OFF -DAQUAGPUSPH_USE_MPI:BOOL=ON -DAQUAGPUSPH_USE_VTK:BOOL=ON -DBUILD_TESTING=ON
    - cmake --build build2D/ --config Release
    - cmake --install build2D/ --config Release
    - cd build2D
    - ctest --output-on-failure -C Release
  artifacts:
    paths:
      - build2D/
      - install2D/

compile-and-test-3D:
  image: "ubuntu:latest"
  stage: build_and_test
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
  before_script:
    - echo 'debconf debconf/frontend select Noninteractive' | debconf-set-selections
    - DEBIAN_FRONTEND=noninteractive apt-get -qq update && apt-get -qq -y --no-install-recommends install tzdata
    - cp /usr/share/zoneinfo/Europe/Madrid /etc/localtime
    - apt-get -qq install -y build-essential git cmake xxd
    - apt-get -qq install -y python3-numpy python3-dev python-is-python3
    - apt-get -qq install -y libxerces-c-dev libmuparser-dev
    - apt-get -qq install -y llvm-dev clang libclang-dev
    - apt-get -qq install -y ocl-icd-opencl-dev pocl-opencl-icd
    - apt-get -qq install -y libopenmpi-dev libvtk9-dev
    - mkdir -p build3D
    - mkdir -p install3D
  script:
    - cmake -B build3D/ -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=install3D -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON -DAQUAGPUSPH_3D:BOOL=ON -DAQUAGPUSPH_USE_MPI:BOOL=ON -DAQUAGPUSPH_USE_VTK:BOOL=ON -DBUILD_TESTING=ON
    - cmake --build build3D/ --config Release
    - cmake --install build3D/ --config Release
    - cd build3D
    - ctest --output-on-failure -C Release
  artifacts:
    paths:
      - buil3D/
      - install3D/

version_job:
  stage: version
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    # - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_COMMIT_BRANCH == 'cicd'
  script:
    - export VERSION_MAJOR=$(cat ${CI_PROJECT_DIRECTORY}/CMakeLists.txt | grep PACKAGE_VERSION_MAJOR | head -1 | awk -F' ' '{print $2}' | awk -F')' '{print $1}')
    - export VERSION_MINOR=$(cat ${CI_PROJECT_DIRECTORY}/CMakeLists.txt | grep PACKAGE_VERSION_MINOR | head -1 | awk -F' ' '{print $2}' | awk -F')' '{print $1}')
    - export VERSION_PATCH=$(cat ${CI_PROJECT_DIRECTORY}/CMakeLists.txt | grep PACKAGE_VERSION_PATCH | head -1 | awk -F' ' '{print $2}' | awk -F')' '{print $1}')
    - echo "TAG=v$VERSION_MAJOR.$VERSION_MINOR.$VERSION_PATCH" >> variables.env
  artifacts:
    reports:
      dotenv: variables.env

release_job:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  needs:
    - job: version_job
      artifacts: true
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    # - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_COMMIT_BRANCH == 'cicd'
  script:
    - echo "running release_job for $TAG"
  release:
    name: 'Release $TAG'
    tag_name: '$TAG.$CI_PIPELINE_IID'
    description: '$TAG.$CI_PIPELINE_IID'
    ref: '$CI_COMMIT_SHA'
